In [1]:
import pandas as pd
df = pd.read_csv('data/eurojackpot_2012_2025_master.csv')
df.head()

,short_date,weekday,draw_date,jackpot,main_numbers,euro_numbers,Match,# of winners,prize / winner,prize fund
0,06.01.2012,Friday,"Friday, 3rd October 2025","€28,695,885",01 02 07 21 27,08 12,5 + 2,0,"€28,695,885","€28,695,885"
1,06.01.2012,Friday,"Friday, 3rd October 2025","€28,695,885",01 02 07 21 27,08 12,5 + 1,3,"€635,080.60","€1,905,242"
2,06.01.2012,Friday,"Friday, 3rd October 2025","€28,695,885",01 02 07 21 27,08 12,5 + 0,20,"€53,723.30","€1,074,466"
3,06.01.2012,Friday,"Friday, 3rd October 2025","€28,695,885",01 02 07 21 27,08 12,4 + 2,32,"€5,538.40","€177,229"
4,06.01.2012,Friday,"Friday, 3rd October 2025","€28,695,885",01 02 07 21 27,08 12,4 + 1,898,€246.70,"€221,537"

In [2]:
print(df.dtypes)

short_date        object
weekday           object
draw_date         object
jackpot           object
main_numbers      object
euro_numbers      object
Match             object
# of winners      object
prize / winner    object
prize fund        object
dtype: object

In [3]:
df['short_date'] = pd.to_datetime(df['short_date'], format='%d.%m.%Y')
df.tail()

,short_date,weekday,draw_date,jackpot,main_numbers,euro_numbers,Match,# of winners,prize / winner,prize fund
11119,2025-12-30,Tuesday,"Friday, 3rd October 2025","€28,695,885",01 02 07 21 27,08 12,2 + 2,"17,015",€33.20,"€564,898"
11120,2025-12-30,Tuesday,"Friday, 3rd October 2025","€28,695,885",01 02 07 21 27,08 12,3 + 1,"34,718",€18.10,"€628,396"
11121,2025-12-30,Tuesday,"Friday, 3rd October 2025","€28,695,885",01 02 07 21 27,08 12,3 + 0,"92,495",€14.90,"€1,378,176"
11122,2025-12-30,Tuesday,"Friday, 3rd October 2025","€28,695,885",01 02 07 21 27,08 12,1 + 2,"87,538",€14.90,"€1,304,316"
11123,2025-12-30,Tuesday,"Friday, 3rd October 2025","€28,695,885",01 02 07 21 27,08 12,2 + 1,"459,029",€9.70,"€4,452,581"

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11124 entries, 0 to 11123
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   short_date      11124 non-null  datetime64[ns]
 1   weekday         11124 non-null  object
 2   draw_date       11124 non-null  object
 3   jackpot         10812 non-null  object
 4   main_numbers    11124 non-null  object
 5   euro_numbers    11124 non-null  object
 6   Match           11124 non-null  object
 7   # of winners    11124 non-null  object
 8   prize / winner  11124 non-null  object
 9   prize fund      11124 non-null  object
dtypes: datetime64[ns](1), object(9)
memory usage: 869.2+ KB

In [5]:
# With null support:
df['jackpot'] = (
    df['jackpot']
    .str.replace('€', '', regex=False)
    .str.replace(',', '', regex=False)
    .astype(float)            # allows null values
)

In [6]:
# With null support:
df['prize fund'] = (
    df['prize fund']
    .str.replace('€', '', regex=False)
    .str.replace(',', '', regex=False)
    .astype('Int64')            # allows null values
)

In [7]:
df['prize / winner'] = (
    df['prize / winner']
    .str.replace('€', '', regex=False)
    .str.replace(',', '', regex=False)
)
df['prize / winner'] = pd.to_numeric(df['prize / winner'], errors='coerce')

In [8]:
df

,short_date,weekday,draw_date,jackpot,main_numbers,euro_numbers,Match,# of winners,prize / winner,prize fund
0,2012-01-06,Friday,"Friday, 3rd October 2025",28695885.0,01 02 07 21 27,08 12,5 + 2,0,28695885.0,28695885
1,2012-01-06,Friday,"Friday, 3rd October 2025",28695885.0,01 02 07 21 27,08 12,5 + 1,3,635080.6,1905242
2,2012-01-06,Friday,"Friday, 3rd October 2025",28695885.0,01 02 07 21 27,08 12,5 + 0,20,53723.3,1074466
3,2012-01-06,Friday,"Friday, 3rd October 2025",28695885.0,01 02 07 21 27,08 12,4 + 2,32,5538.4,177229
4,2012-01-06,Friday,"Friday, 3rd October 2025",28695885.0,01 02 07 21 27,08 12,4 + 1,898,246.7,221537
...,...,...,...,...,...,...,...,...,...,...
11119,2025-12-30,Tuesday,"Friday, 3rd October 2025",28695885.0,01 02 07 21 27,08 12,2 + 2,"17,015",33.2,564898
11120,2025-12-30,Tuesday,"Friday, 3rd October 2025",28695885.0,01 02 07 21 27,08 12,3 + 1,"34,718",18.1,628396
11121,2025-12-30,Tuesday,"Friday, 3rd October 2025",28695885.0,01 02 07 21 27,08 12,3 + 0,"92,495",14.9,1378176
11122,2025-12-30,Tuesday,"Friday, 3rd October 2025",28695885.0,01 02 07 21 27,08 12,1 + 2,"87,538",14.9,1304316
11123,2025-12-30,Tuesday,"Friday, 3rd October 2025",28695885.0,01 02 07 21 27,08 12,2 + 1,"459,029",9.7,4452581

In [9]:
df['main_numbers'] = df['main_numbers'].apply(lambda x: [int(n) for n in x.split()])
df['euro_numbers'] = df['euro_numbers'].apply(lambda x: [int(n) for n in x.split()])

In [10]:
row = df.iloc[7222]
print(row)

short_date               2022-11-18 00:00:00
weekday                               Friday
draw_date         Friday, 18th November 2022
jackpot                           26100767.0
main_numbers            [13, 14, 25, 28, 42]
euro_numbers                        [11, 12]
Match                                  1 + 2
# of winners                          66,766
prize / winner                          16.8
prize fund                           1121669
Name: 7222, dtype: object

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11124 entries, 0 to 11123
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   short_date      11124 non-null  datetime64[ns]
 1   weekday         11124 non-null  object
 2   draw_date       11124 non-null  object
 3   jackpot         10812 non-null  float64
 4   main_numbers    11124 non-null  object
 5   euro_numbers    11124 non-null  object
 6   Match           11124 non-null  object
 7   # of winners    11124 non-null  object
 8   prize / winner  11098 non-null  float64
 9   prize fund      11124 non-null  Int64
dtypes: Int64(1), datetime64[ns](1), float64(2), object(6)
memory usage: 880.1+ KB

In [12]:
df['# of winners'] = (
    df['# of winners']
    .str.replace(',', '', regex=False)
)

df['# of winners'] = pd.to_numeric(df['# of winners'], errors='coerce').astype('Int64')

In [13]:
df

,short_date,weekday,draw_date,jackpot,main_numbers,euro_numbers,Match,# of winners,prize / winner,prize fund
0,2012-01-06,Friday,"Friday, 3rd October 2025",28695885.0,"[1, 2, 7, 21, 27]","[8, 12]",5 + 2,0,28695885.0,28695885
1,2012-01-06,Friday,"Friday, 3rd October 2025",28695885.0,"[1, 2, 7, 21, 27]","[8, 12]",5 + 1,3,635080.6,1905242
2,2012-01-06,Friday,"Friday, 3rd October 2025",28695885.0,"[1, 2, 7, 21, 27]","[8, 12]",5 + 0,20,53723.3,1074466
3,2012-01-06,Friday,"Friday, 3rd October 2025",28695885.0,"[1, 2, 7, 21, 27]","[8, 12]",4 + 2,32,5538.4,177229
4,2012-01-06,Friday,"Friday, 3rd October 2025",28695885.0,"[1, 2, 7, 21, 27]","[8, 12]",4 + 1,898,246.7,221537
...,...,...,...,...,...,...,...,...,...,...
11119,2025-12-30,Tuesday,"Friday, 3rd October 2025",28695885.0,"[1, 2, 7, 21, 27]","[8, 12]",2 + 2,17015,33.2,564898
11120,2025-12-30,Tuesday,"Friday, 3rd October 2025",28695885.0,"[1, 2, 7, 21, 27]","[8, 12]",3 + 1,34718,18.1,628396
11121,2025-12-30,Tuesday,"Friday, 3rd October 2025",28695885.0,"[1, 2, 7, 21, 27]","[8, 12]",3 + 0,92495,14.9,1378176
11122,2025-12-30,Tuesday,"Friday, 3rd October 2025",28695885.0,"[1, 2, 7, 21, 27]","[8, 12]",1 + 2,87538,14.9,1304316
11123,2025-12-30,Tuesday,"Friday, 3rd October 2025",28695885.0,"[1, 2, 7, 21, 27]","[8, 12]",2 + 1,459029,9.7,4452581

In [14]:
df["Match"] = df["Match"].astype(str)

In [15]:
df['jackpot'].min()

5075566.0

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11124 entries, 0 to 11123
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   short_date      11124 non-null  datetime64[ns]
 1   weekday         11124 non-null  object
 2   draw_date       11124 non-null  object
 3   jackpot         10812 non-null  float64
 4   main_numbers    11124 non-null  object
 5   euro_numbers    11124 non-null  object
 6   Match           11124 non-null  object
 7   # of winners    11124 non-null  Int64
 8   prize / winner  11098 non-null  float64
 9   prize fund      11124 non-null  Int64
dtypes: Int64(2), datetime64[ns](1), float64(2), object(5)
memory usage: 890.9+ KB

In [17]:
df["Match"] = df["Match"].astype(str)

In [21]:
df["# of winners"] = df["# of winners"].astype(int)

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11124 entries, 0 to 11123
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   short_date      11124 non-null  datetime64[ns]
 1   weekday         11124 non-null  object
 2   draw_date       11124 non-null  object
 3   jackpot         10812 non-null  float64
 4   main_numbers    11124 non-null  object
 5   euro_numbers    11124 non-null  object
 6   Match           11124 non-null  object
 7   # of winners    11124 non-null  int32
 8   prize / winner  11098 non-null  float64
 9   prize fund      11124 non-null  Int64
dtypes: Int64(1), datetime64[ns](1), float64(2), int32(1), object(5)
memory usage: 836.6+ KB

In [23]:
df.to_csv('data/eurojackpot_data.csv', index=False)